"use client"

import { experience, about } from "@/lib/portfolio-data"
import { motion } from "framer-motion"
import { Terminal, GraduationCap } from "lucide-react"

export function ExperienceSection() {
  const containerVariants = { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.2, delayChildren: 0.2 } } }
  const itemVariants = { hidden: { opacity: 0, x: -10 }, visible: { opacity: 1, x: 0, transition: { duration: 0.4 } } }
  return <section id="experience" className="relative overflow-hidden border-t border-primary/10 px-4 py-32"><div className="absolute left-0 top-0 h-full w-px bg-gradient-to-b from-transparent via-primary/20 to-transparent" /><motion.div className="relative mx-auto max-w-4xl" initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} transition={{ duration: 0.6 }} viewport={{ once: true, margin: "-100px" }}>
    <div className="mb-16 space-y-4"><div className="flex items-center gap-4"><h2 className="text-4xl font-bold uppercase tracking-tighter text-foreground md:text-5xl">Exp_Timeline</h2><div className="h-px flex-1 bg-primary/20" /><span className="hidden text-[10px] font-mono uppercase tracking-widest text-primary/50 sm:block">[INDEX: 04]</span></div><p className="text-lg font-mono text-muted-foreground">{`// Shipping measurable outcomes across product and infrastructure.`}</p></div>
    <motion.div className="space-y-12" variants={containerVariants} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }}>{experience.map((job, index) => <motion.article key={job.company} variants={itemVariants} className="group relative pl-12"><div className="absolute left-0 top-0 flex flex-col items-center"><div className="flex h-10 w-10 items-center justify-center border border-primary/40 bg-card transition-all group-hover:border-primary"><Terminal size={14} className="text-primary/60 group-hover:text-primary" /></div><div className="min-h-[100px] w-px flex-1 bg-primary/10" /></div><div className="border border-primary/10 bg-card p-8 transition-all hover:border-primary/30"><div className="mb-6 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div className="space-y-1"><div className="mb-2 inline-flex border border-primary/10 bg-primary/5 px-2 py-0.5 text-[9px] font-mono uppercase text-primary">Completed_Process</div><h3 className="text-2xl font-bold uppercase tracking-tight text-foreground">{job.position}</h3><p className="text-sm tracking-wide text-primary font-mono">@ {job.company}</p></div><div className="h-fit border border-primary/5 bg-muted px-3 py-1 text-[10px] uppercase text-muted-foreground font-mono">{job.duration}</div></div><p className="mb-6 border-l border-primary/10 pl-4 text-xs italic leading-relaxed text-muted-foreground/90 font-mono">&gt; {job.description}</p><div className="grid gap-4 sm:grid-cols-2">{job.achievements.map((achievement) => <div key={achievement} className="flex items-start gap-3 border border-primary/5 bg-muted/30 p-3 text-[10px] uppercase text-muted-foreground font-mono"><div className="mt-0.5 h-3 w-1 shrink-0 bg-primary/40" />{achievement}</div>)}</div></div></motion.article>)}</motion.div>
    <div className="mt-16 flex items-start gap-5 border-t border-primary/10 pt-8"><div className="flex h-10 w-10 shrink-0 items-center justify-center border border-primary/30 text-primary"><GraduationCap size={16} /></div><div><p className="text-[10px] uppercase tracking-widest text-primary font-mono">Education_Signal</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground font-mono">{about.education}</p></div></div>
  </motion.div></section>
}
