export const socials = [
  { id: 1, name: "github", icon: "Github", link: "https://github.com/MARVELGARR" },
  { id: 2, name: "linkedin", icon: "Linkedin", link: "https://linkedin.com/in/marvellous-obatale" },
  { id: 3, name: "twitter", icon: "Twitter", link: "https://twitter.com/MARVEL_GARRA" },
  { id: 4, name: "email", icon: "Mail", link: "mailto:marvellousobatale@gmail.com" },
  { id: 5, name: "hashnode", icon: "FileText", link: "https://marvelgarra.hashnode.dev/" },
]

export const heroContent = { name: "Marvellous Obatale", title: "Full-Stack Developer", description: "Building performant web applications with React, Next.js, TypeScript, and Node.js. 2+ years of experience delivering 35% performance improvements, 25% engagement growth, and systems that scale.", cta: "View My Work", location: "Lagos, Nigeria", phone: "+2348152795806" }

export const skills = [
  { category: "Frontend", items: ["JavaScript (ES6+)", "TypeScript", "React", "Next.js", "TailwindCSS", "Framer Motion", "SCSS", "shadcn/ui"].map((name) => ({ name, level: "Advanced" })) },
  { category: "Backend", items: ["Node.js", "Express.js", "MongoDB", "PostgreSQL", "Prisma", "REST APIs"].map((name) => ({ name, level: "Advanced" })) },
  { category: "Tools & Libraries", items: ["Git/GitHub", "TanStack Query", "Redux Toolkit", "Zod", "React Hook Form", "Jest", "AWS S3", "Auth.js"].map((name) => ({ name, level: "Advanced" })) },
]

export const projects = [
  { id: 1, title: "Full Ledger System", description: "A financial ledger platform designed for reliable transaction recording, account reconciliation, and audit-ready reporting.", technologies: ["Next.js", "TypeScript", "PostgreSQL", "Prisma"], github: "https://github.com/MARVELGARR", live: "#", image: "/images/projects/desktop-design.jpg", difficulty: "Hard", category: "Production", status: "Featured", impact: "Structured financial workflows around traceability and consistency.", architecture: "Typed full-stack application with relational data modeling, validation, and service boundaries." },
  { id: 2, title: "Wallet Simulation API", description: "A backend simulation for wallet balances and transfers, built to explore safe financial operations and predictable API behavior.", technologies: ["Node.js", "Express.js", "PostgreSQL", "REST API"], github: "https://github.com/MARVELGARR", live: "#", image: "/images/projects/ip tracker.jpg", difficulty: "Hard", category: "Backend", status: "Featured", impact: "Demonstrates transaction-minded API design and edge-case handling.", architecture: "REST endpoints with validated inputs, persistence, and clear separation between routes and domain logic." },
  { id: 3, title: "Smart Visitor Counter", description: "An IoT-minded visitor counting and lighting system concept connecting sensing, automation, and useful operational feedback.", technologies: ["JavaScript", "IoT", "Automation", "Systems Design"], github: "https://github.com/MARVELGARR", live: "#", image: "/images/projects/active-states.jpg", difficulty: "Normal", category: "Systems", status: "Featured", impact: "Connects software thinking to real-world infrastructure and energy awareness.", architecture: "Event-driven sensor inputs mapped to occupancy state, lighting logic, and monitoring output." },
  { id: 4, title: "Country Explorer", description: "Interactive country information explorer with advanced search and filtering across capitals, populations, borders, and time zones.", technologies: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"], github: "https://github.com/MARVELGARR/restcountries", live: "https://restcountries-delta.vercel.app/", image: "/images/projects/rest country.jpg", difficulty: "Normal", category: "Frontend", status: "Live", impact: "Turns a dense public dataset into a fast, approachable discovery tool.", architecture: "Responsive client interface with API data, search, filtering, and motion-led feedback." },
  { id: 5, title: "IP Address Tracker", description: "Geolocation tool that tracks IP addresses and displays location data on an interactive map with timezone information.", technologies: ["Next.js", "TailwindCSS", "Leaflet", "GeoIP API"], github: "https://github.com/MARVELGARR/IP-ADDRESS-TRACKER", live: "https://elaborate-frangipane-b3631d.netlify.app/", image: "/images/projects/ip tracker.jpg", difficulty: "Hard", category: "Frontend", status: "Live", impact: "Makes location intelligence legible through a focused map workflow.", architecture: "API-driven search paired with Leaflet rendering and responsive layout states." },
  { id: 6, title: "Comment Section App", description: "Full-stack comment application with authentication, persistent storage, editing, deletion, and threaded replies.", technologies: ["Next.js", "MongoDB", "Prisma", "Auth.js"], github: "https://github.com/MARVELGARR/commentsection-app", live: "https://commentsection-app-3fhz-fdmtfi9w3-marvelgarr.vercel.app/", image: "/images/projects/active-states.jpg", difficulty: "Hard", category: "Full Stack", status: "Live", impact: "Shows end-to-end ownership of auth, data, and interaction design.", architecture: "Authenticated full-stack flow with Prisma persistence and nested comment relationships." },
]

export const experience = [
  { company: "Foremedia", position: "Frontend Developer", duration: "Oct 2024 – Present", description: "Leading custom React video player development and a role-based admin dashboard with content scheduling and analytics.", achievements: ["35% performance improvement through optimization", "TanStack Query caching reduced network requests by 30%", "Mentored junior developers on architecture patterns"] },
  { company: "Fatherland.io", position: "Full-Stack Developer", duration: "Jan 2024 – Apr 2024", description: "Built real-time product experiences with Next.js, Prisma, and MongoDB, and shipped secure global payments across Stripe, PayPal, and Paystack.", achievements: ["25% user engagement increase with real-time chat", "Multi-payment gateway integration", "40% administrative overhead reduction through CMS"] },
  { company: "Transmission Company of Nigeria", position: "Engineering Intern", duration: "Jun 2019 – Dec 2019", description: "Diagnosed and resolved 50+ SCADA network faults for critical infrastructure monitoring, achieving sub-5ms latency and 99% data accuracy.", achievements: ["50+ SCADA network faults resolved", "Sub-5ms latency achieved", "99% data accuracy maintained"] },
]

export const about = { intro: "Full-Stack Developer with 2+ years of experience building performant web applications and measurable product outcomes.", bio: "I'm passionate about creating elegant solutions to complex problems. I specialize in scalable web applications, performance, user experience, and clean architecture across the stack.", education: "B.Eng. in Information & Communication Technology — Elizade University (Graduated Sept 2021)" }
